FROM decidim/decidim:0.19.0
LABEL maintainer="info@codegram.com"

ENV RAILS_ENV=development
ENV PORT=3000

RUN apt-get install -y postgresql-client

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
RUN bundle install
RUN bundle exec rake assets:precompile
