FROM decidim/decidim:0.23.1
LABEL maintainer="sistemas@aspgems.com"

ENV RAILS_ENV=development
ENV PORT=3000

RUN apt-get update
RUN apt-get install -y postgresql-client --fix-missing

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
RUN bundle install
RUN bundle exec rake assets:precompile
